[package]
name = "ystudio-zero"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="4.0.8", features=["derive"]}
eframe = "0.23.0"
egui = "0.23.0"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
serialport="4"
csv = "1.1"
egui-plotter = "0.3.0"
egui_plot = "0.23.0"
